version: 0.0
os: linux
files:
  - source: / # Ini akan memindahkan SEMUA file dan folder dari root artefak
    destination: /home/ubuntu/

hooks:
  ApplicationStart:
    - location: start.sh
      timeout: 60
      runas: ubuntu