version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.20
    commands:
      - go version
  build:
    commands:
      - echo "Starting Go build..."
      - go build -o tescicd main.go
      - ls -lh
      - file tescicd

artifacts:
  files:
    - '**/*'           # Tangkap semua file
  discard-paths: no     # Pertahankan struktur folder
