version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.x
    commands:
      - echo Installing Go modules...
  build:
    commands:
      - echo Building Go app...
      - go build -o tescicd main.go
artifacts:
  files:
    - tescicd
