version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.20
    commands:
      - go version
  build:
    commands:
      - echo "Building Go app..."
      - pwd                      # Tampilkan direktori kerja
      - ls -lh                   # Lihat file yang tersedia
      - go build -o tescicd main.go
      - chmod +x tescicd
      - ls -lh tescicd
      - file tescicd
      
artifacts:
  files:
    - tescicd
    - appspec.yml
    - start.sh
  discard-paths: no